# Generated by Django 4.2.7 on 2026-06-03 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='case_creator',
            field=models.CharField(blank=True, max_length=100, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='case_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='用例类型'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='clarifying_questions',
            field=models.JSONField(blank=True, default=list, verbose_name='澄清问题'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='coverage_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='覆盖率报告'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='dedupe_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='去重报告'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='iteration',
            field=models.CharField(blank=True, max_length=100, verbose_name='归属迭代'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='pipeline_artifacts',
            field=models.JSONField(blank=True, default=dict, verbose_name='流水线产物'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='requirement_ids',
            field=models.JSONField(default=list, verbose_name='需求ID列表'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='scenario_matrix',
            field=models.JSONField(blank=True, default=list, verbose_name='场景矩阵'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='strategy_matrix',
            field=models.JSONField(blank=True, default=list, verbose_name='测试策略矩阵'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='structured_requirements',
            field=models.JSONField(blank=True, default=list, verbose_name='结构化需求'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_cases_json',
            field=models.JSONField(blank=True, default=list, verbose_name='结构化测试用例'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_cases_review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('revision_requested', '需修改')], default='pending', max_length=30, verbose_name='测试用例审核状态'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_cases_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='测试用例审核时间'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_cases_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_test_case_tasks', to=settings.AUTH_USER_MODEL, verbose_name='测试用例审核人'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_points',
            field=models.JSONField(blank=True, default=list, verbose_name='测试点'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_points_review_status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已审核'), ('revision_requested', '需修改')], default='pending', max_length=30, verbose_name='测试点审核状态'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_points_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='测试点审核时间'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='test_points_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_test_point_tasks', to=settings.AUTH_USER_MODEL, verbose_name='测试点审核人'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='testability_report',
            field=models.JSONField(blank=True, default=dict, verbose_name='可测试性报告'),
        ),
    ]
