# Generated by Django 4.2.7 on 2026-06-03 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requirement_analysis', '0003_testcasegenerationtask_case_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='selected_template_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='选中模板名称'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='source_extract_error',
            field=models.TextField(blank=True, verbose_name='源文件解析错误'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='source_extract_status',
            field=models.CharField(choices=[('pending', '待解析'), ('parsed', '已解析'), ('failed', '解析失败')], default='pending', max_length=20, verbose_name='源文件解析状态'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='requirement_sources/%Y/%m/', verbose_name='PRD源文件'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='source_file_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='源文件类型'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='template_file',
            field=models.FileField(blank=True, null=True, upload_to='testcase_templates/%Y/%m/', verbose_name='任务用例模板'),
        ),
        migrations.AddField(
            model_name='testcasegenerationtask',
            name='template_schema',
            field=models.JSONField(blank=True, default=dict, verbose_name='用例模板结构'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='model_type',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('siliconflow', '硅基流动'), ('zhipu', '智谱'), ('other', '其他')], max_length=20, verbose_name='模型类型'),
        ),
        migrations.AlterField(
            model_name='aimodelconfig',
            name='role',
            field=models.CharField(choices=[('writer', '测试用例编写专家'), ('reviewer', '测试评审专家'), ('vision', '视觉解析模型'), ('browser_use_text', 'Browser Use - 文本模式')], max_length=20, verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='TestCaseTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名称')),
                ('template_file', models.FileField(blank=True, null=True, upload_to='testcase_templates/default/%Y/%m/', verbose_name='模板文件')),
                ('template_schema', models.JSONField(blank=True, default=dict, verbose_name='模板结构')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '测试用例模板配置',
                'verbose_name_plural': '测试用例模板配置',
                'db_table': 'testcase_template_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
